config/routes.rb
Rails.application.routes.draw do
  resources :favorites
  resources :combos
  resources :tag_suggestions
  resources :tags
  resources :price_suggestions
  resources :products
  devise_for :users
  #resources :application, only[:index]
  #get "/application/:page" => "application#show"
  get "/application/index" =>"application#index"
  get "/products/index" => "tags#index"
  #get "/application/index" => "product#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  include UserConcern
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  #before_action :only_admins, only: [ :index]

  # GET /favorites
  # GET /favorites.json
  def index
    if user_signed_in? && is_admin?
      @favorites = Favorite.all
    else
      @favorites = current_user.favorites
    end
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @favorite, notice: 'Favorite was successfully created.' }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:user_id, :product_id)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_for(favorite) do |f| %>
  <% if favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user.email %></td>
        <td><%= favorite.product.title   %></td>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite.user.email %>
</p>

<p>
  <strong>Product:</strong>
  <%= @favorite.product.title %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>