config/routes.rb
Rails.application.routes.draw do
  resources :favorites
  resources :combos
  resources :tag_suggestions
  resources :tags
  resources :price_suggestions
  resources :products
  devise_for :users
  #resources :application, only[:index]
  #get "/application/:page" => "application#show"
  get "/application/index" =>"application#index"
  get "/products/index" => "tags#index"
  #get "/application/index" => "product#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag_suggestion.rb
class TagSuggestion < ApplicationRecord
  belongs_to :user
  belongs_to :product
  before_create :default_values

  def default_values
    self.approved = false
  end
end

app/controllers/tag_suggestions_controller.rb
class TagSuggestionsController < ApplicationController
  include UserConcern
  before_action :authenticate_user!
  before_action :set_tag_suggestion, only: [:show, :edit, :update, :destroy]
  before_action :only_admins, except: [:new]
  

  # GET /tag_suggestions
  # GET /tag_suggestions.json
  def index
    @tag_suggestions = TagSuggestion.all
  end

  # GET /tag_suggestions/1
  # GET /tag_suggestions/1.json
  def show
  end

  # GET /tag_suggestions/new
  def new
    @tag_suggestion = TagSuggestion.new
  end

  # GET /tag_suggestions/1/edit
  def edit
  end

  # POST /tag_suggestions
  # POST /tag_suggestions.json
  def create
    @tag_suggestion = TagSuggestion.new(tag_suggestion_params)
    @tag_suggestion.user_id = current_user.id

    respond_to do |format|
      if @tag_suggestion.save
        format.html { redirect_to @tag_suggestion, notice: 'Tag suggestion was successfully created.' }
        format.json { render :show, status: :created, location: @tag_suggestion }
      else
        format.html { render :new }
        format.json { render json: @tag_suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tag_suggestions/1
  # PATCH/PUT /tag_suggestions/1.json
  def update
    respond_to do |format|
      if @tag_suggestion.update(tag_suggestion_params)
        format.html { redirect_to @tag_suggestion, notice: 'Tag suggestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag_suggestion }
      else
        format.html { render :edit }
        format.json { render json: @tag_suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tag_suggestions/1
  # DELETE /tag_suggestions/1.json
  def destroy
    @tag_suggestion.destroy
    respond_to do |format|
      format.html { redirect_to tag_suggestions_url, notice: 'Tag suggestion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag_suggestion
      @tag_suggestion = TagSuggestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_suggestion_params
      params.require(:tag_suggestion).permit(:title, :product_id)
    end
end

app/helpers/tag_suggestions_helper.rb
module TagSuggestionsHelper
end

app/views/tag_suggestions/_form.html.erb
<%= form_for(tag_suggestion) do |f| %>
  <% if tag_suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag_suggestion.errors.count, "error") %> prohibited this tag_suggestion from being saved:</h2>

      <ul>
      <% tag_suggestion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tag_suggestions/edit.html.erb
<h1>Editing Tag Suggestion</h1>

<%= render 'form', tag_suggestion: @tag_suggestion %>

<%= link_to 'Show', @tag_suggestion %> |
<%= link_to 'Back', tag_suggestions_path %>

app/views/tag_suggestions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tag Suggestions</h1>

<table class ="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Product</th>
      <th>Approved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tag_suggestions.each do |tag_suggestion| %>
      <tr>
        <td><%= tag_suggestion.title %></td>
        <td><%= tag_suggestion.user.email %></td>
        <td><%= tag_suggestion.product.title %></td>
        <td><%= tag_suggestion.approved %></td>
        <td><%= link_to 'Show', tag_suggestion %></td>
        <td><%= link_to 'Edit', edit_tag_suggestion_path(tag_suggestion) %></td>
        <td><%= link_to 'Destroy', tag_suggestion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag Suggestion', new_tag_suggestion_path %>

app/views/tag_suggestions/new.html.erb
<h1>New Tag Suggestion</h1>

<%= render 'form', tag_suggestion: @tag_suggestion %>

<%= link_to 'Back', tag_suggestions_path %>

app/views/tag_suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tag_suggestion.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @tag_suggestion.user.email %>
</p>

<p>
  <strong>Product:</strong>
  <%= @tag_suggestion.product.title %>
</p>

<%= link_to 'Edit', edit_tag_suggestion_path(@tag_suggestion) %> |
<%= link_to 'Back', tag_suggestions_path %>