config/routes.rb
Rails.application.routes.draw do
  resources :favorites
  resources :combos
  resources :tag_suggestions
  resources :tags
  resources :price_suggestions
  resources :products
  devise_for :users
  #resources :application, only[:index]
  #get "/application/:page" => "application#show"
  get "/application/index" =>"application#index"
  get "/products/index" => "tags#index"
  #get "/application/index" => "product#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/price_suggestion.rb
class PriceSuggestion < ApplicationRecord
  belongs_to :user
  belongs_to :product
  before_create :default_values

  def default_values
    self.approved = false
  end
end

app/controllers/price_suggestions_controller.rb
class PriceSuggestionsController < ApplicationController
  include UserConcern
  before_action :set_price_suggestion, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :only_admins, except: [:new]
  
  # GET /price_suggestions
  # GET /price_suggestions.json
  def index
    @price_suggestions = PriceSuggestion.all
  end

  # GET /price_suggestions/1
  # GET /price_suggestions/1.json
  def show
    render template: "application/#{params[:page]}"
  end

  # GET /price_suggestions/new
  def new
    @price_suggestion = PriceSuggestion.new
  end

  # GET /price_suggestions/1/edit
  def edit
  end

  # POST /price_suggestions
  # POST /price_suggestions.json
  def create
    @price_suggestion = PriceSuggestion.new(price_suggestion_params)
    @price_suggestion.user_id = current_user.id

    respond_to do |format|
      if @price_suggestion.save
        format.html { redirect_to @price_suggestion, notice: 'Price suggestion was successfully created.' }
        format.json { render :show, status: :created, location: @price_suggestion }
      else
        format.html { render :new }
        format.json { render json: @price_suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_suggestions/1
  # PATCH/PUT /price_suggestions/1.json
  def update
    respond_to do |format|
      if @price_suggestion.update(price_suggestion_params)
        format.html { redirect_to @price_suggestion, notice: 'Price suggestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @price_suggestion }
      else
        format.html { render :edit }
        format.json { render json: @price_suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_suggestions/1
  # DELETE /price_suggestions/1.json
  def destroy
    @price_suggestion.destroy
    respond_to do |format|
      format.html { redirect_to price_suggestions_url, notice: 'Price suggestion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price_suggestion
      @price_suggestion = PriceSuggestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_suggestion_params
      params.require(:price_suggestion).permit(:product_id, :price)
    end
end

app/helpers/price_suggestions_helper.rb
module PriceSuggestionsHelper
end

app/views/price_suggestions/_form.html.erb
<%= form_for(price_suggestion) do |f| %>
  <% if price_suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price_suggestion.errors.count, "error") %> prohibited this price_suggestion from being saved:</h2>

      <ul>
      <% price_suggestion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/price_suggestions/edit.html.erb
<h1>Editing Price Suggestion</h1>

<%= render 'form', price_suggestion: @price_suggestion %>

<%= link_to 'Show', @price_suggestion %> |
<%= link_to 'Back', price_suggestions_path %>

app/views/price_suggestions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Price Suggestions</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Price</th>
      <th>Approved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @price_suggestions.each do |price_suggestion| %>
      <tr>
        <td><%= price_suggestion.user.email %></td>
        <td><%= price_suggestion.product.title %></td>
        <td><%= price_suggestion.price %></td>
        <td><%= price_suggestion.approved %></td>
        <td><%= link_to 'Show', price_suggestion %></td>
        <td><%= link_to 'Edit', edit_price_suggestion_path(price_suggestion) %></td>
        <td><%= link_to 'Destroy', price_suggestion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price Suggestion', new_price_suggestion_path %>

app/views/price_suggestions/new.html.erb
<h1>New Price Suggestion</h1>

<%= render 'form', price_suggestion: @price_suggestion %>

<%= link_to 'Back', price_suggestions_path %>

app/views/price_suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @price_suggestion.user.id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @price_suggestion.product.id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @price_suggestion.price %>
</p>

<%= link_to 'Edit', edit_price_suggestion_path(@price_suggestion) %> |
<%= link_to 'Back', price_suggestions_path %>